### ISSUE TITLE
Error with Bytecodeoutline Eclipse plugin

### ISSUE THREAD

**Issue by xbotuk** [iloveeclipse/bytecodeoutline#3]
I have Eclipse 2020-09 that requires Java 11 to run and installed bytecode viewer from marketplace, but when starting I'm getting this error. Can you look into fixing this soon please?

!ENTRY org.eclipse.jdt.bcoview 4 0 2020-12-07 20:16:27.826
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.bcoview [1179]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"] because it is exposed to package 'org.objectweb.asm' from resources org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="8.0.1.v20200420-1007"; osgi.identity="org.objectweb.asm"] and org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="7.2.0.v20191010-1910"; osgi.identity="org.objectweb.asm"] via two dependency chains.

Chain 1:
  org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm)(bundle-version>=7.0.0))
     |
    provide: osgi.wiring.bundle: org.objectweb.asm
  org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="8.0.1.v20200420-1007"; osgi.identity="org.objectweb.asm"]

Chain 2:
  org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm.commons)(bundle-version>=7.0.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="7.2.0.v20191010-1910"; osgi.wiring.bundle="org.objectweb.asm.commons"
  org.objectweb.asm.commons [osgi.identity; type="osgi.bundle"; version:Version="7.2.0.v20191010-1910"; osgi.identity="org.objectweb.asm.commons"]
    import: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=7.2.0)(!(version>=7.3.0))))
     |
    export: osgi.wiring.package: org.objectweb.asm
  org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="7.2.0.v20191010-1910"; osgi.identity="org.objectweb.asm"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Comment by iloveeclipse** [comment]
You seem to have multiple asm versions in the platform (7.0.0, 7.2.0 and 8.0.1).
 Please consider to check where the old versions are coming from and remove that, or update to 8.0.1.
You can add this https://download.eclipse.org/tools/orbit/downloads/drops/R20200831200620/repository as update site and update ASM bundles.
