### ISSUE TITLE
BCO doesn't work if IDE contains different versions of asm libraries

### ISSUE THREAD

**Issue by SteveKunG** [iloveeclipse/bytecodeoutline#6]
As title said, it cannot compile java class version 60.
Eclipse Version: 2021-06 (4.20.0)
Eclipse Build id: 20210612-2011

![image](https://user-images.githubusercontent.com/6128413/122785855-eb2afb00-d2dd-11eb-827e-184b6f38a75c.png)

**Comment by iloveeclipse** [comment]
Please attach error log. I can't reproduce.
![image](https://user-images.githubusercontent.com/964108/122789525-b0ae6780-d2b7-11eb-8df9-c50e532c8ff0.png)

**Comment by SteveKunG** [comment]
Just got another issue same as #5 after re-install your plugin. I can't find any bytecode tab.

**Comment by iloveeclipse** [comment]
> Please attach error log. I can't reproduce.

**Comment by SteveKunG** [comment]
Sorry for didn't answer your question. Here's log.

https://gist.github.com/SteveKunG/bc79acaf75ebea4712493a76af39cf57
![image](https://user-images.githubusercontent.com/6128413/122795710-cb003980-d2e7-11eb-8566-7ec0589ec7e8.png)

**Comment by iloveeclipse** [comment]
```
!SESSION 2021-06-18 11:02:56.173 -----------------------------------------------
eclipse.buildId=4.19.0.I20210303-1800
java.version=16.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.jdt.bcoview 4 0 2021-06-19 17:06:33.564
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.bcoview [671]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"] because it is exposed to package 'org.objectweb.asm' from resources org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="9.1.0.v20210209-1849"; osgi.identity="org.objectweb.asm"] and org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="8.0.1.v20200420-1007"; osgi.identity="org.objectweb.asm"] via two dependency chains.

Chain 1:
  org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm)(bundle-version>=7.0.0))
     |
    provide: osgi.wiring.bundle: org.objectweb.asm
  org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="9.1.0.v20210209-1849"; osgi.identity="org.objectweb.asm"]

Chain 2:
  org.eclipse.jdt.bcoview [osgi.identity; type="osgi.bundle"; version:Version="1.0.1.202006062100"; osgi.identity="org.eclipse.jdt.bcoview"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm.commons)(bundle-version>=7.0.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="8.0.1.v20200420-1007"; osgi.wiring.bundle="org.objectweb.asm.commons"
  org.objectweb.asm.commons [osgi.identity; type="osgi.bundle"; version:Version="8.0.1.v20200420-1007"; osgi.identity="org.objectweb.asm.commons"]
    import: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=8.0.1)(!(version>=8.1.0))))
     |
    export: osgi.wiring.package: org.objectweb.asm
  org.objectweb.asm [osgi.identity; type="osgi.bundle"; version:Version="8.0.1.v20200420-1007"; osgi.identity="org.objectweb.asm"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
 ```

**Comment by iloveeclipse** [comment]
Thanks for the logs. That's #5.
There are different asm bundles in the platform that have not same version, if you can find who pulls in them, you can find who could be uninstalled. BCO requires both asm bundles **in same** version.
